### PR TITLE
Test cases showing that target module can be specified when building an RGF

### PR DESCRIPTION
**Pull request by dpad**
Example test cases include:
* A function defined in a submodule but specified to use its parent module's cache -- and thus uses the parent module's scope.
* A function defined in a precompiled module that uses another precompiled module (without specifying the module cache, this function throws a `KeyError` as shown in the test case).

These tests work as part of #20 as an initial step towards addressing the behaviour I reported in https://github.com/SciML/ModelingToolkit.jl/issues/678

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@c42f could you comment on whether you'd expect this to be safe with the way `RuntimeGeneratedFunctions.init(mod)` works? Is this safe as long as that module is init'd?

**Comment by c42f** [comment]
Yeah I think this should be safe.

At this point (now that users have to explicitly call `init`) I think we may have just outgrown the macro version of the constructor - it's basically only "helping" by acting as a shortcut for specifying `@__MODULE__` in the constructor. But really that might just be obscuring things more than being helpful, and it seems we could get rid of the macro entirely.

So give https://github.com/SciML/RuntimeGeneratedFunctions.jl/pull/20 a try? If that helps and seems like a cleaner solution it would still be nice to have the relevant tests from here.

**Comment by ChrisRackauckas** [comment]
Indeed I think #20 is nice and clean, but the tests from here are good.

**Comment by dpad** [comment]
@ChrisRackauckas @c42f Thank you both for your comments. #20 is indeed a good solution for the first part of my issue, so I've changed this PR to add only the test cases.

**Comment by dpad** [comment]
FYI, the CI seems to have failed on a `@belapsed` timing test. They all pass on my local machine.

**Comment by c42f** [comment]
As discussed in #21 I was afraid #20 would lead to problems. So I've put an alternative in #22 instead.

**Pull request closed without merging**
